import type { MarketProfile, PolicyRecord } from "@/lib/types";

const reviewed = "2026-09-18";

export const policies: PolicyRecord[] = [
  {
    id: "ferc-order-2023",
    title: "FERC Order No. 2023 — Generator Interconnection Reform",
    jurisdiction: "Federal",
    region: "United States",
    policyType: "Interconnection reform",
    status: "Effective",
    effectiveDate: "2023-11-06",
    agency: "Federal Energy Regulatory Commission",
    issueAreas: ["Generator interconnection", "Transmission", "Queue reform"],
    summary:
      "FERC revised pro forma generator interconnection procedures and agreements, including a first-ready, first-served cluster study process, readiness requirements, and other queue reforms.",
    whyItMatters:
      "Data center power availability depends partly on the pace at which new generation and associated network upgrades can move through interconnection processes. This rule changes the upstream development framework used by public utilities.",
    exposure: {
      powerAvailability: "Elevated",
      utilityCost: "Medium",
      interconnectionTimeline: "Elevated",
      siteSelection: "Medium",
      renewableRequirements: "Low",
      capex: "Medium",
      opex: "Low",
      regulatoryUncertainty: "Medium",
    },
    teams: ["Energy", "Site Selection", "Finance", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The final rule requires revised pro forma generator interconnection procedures and agreements.",
      "The rule adopts a first-ready, first-served cluster study process and readiness requirements.",
    ],
    source: {
      label: "FERC fact sheet: Improvements to Generator Interconnection Procedures and Agreements",
      url: "https://www.ferc.gov/news-events/news/fact-sheet-improvements-generator-interconnection-procedures-and-agreements",
      publishedDate: "2023-07-27",
      sourceType: "Primary",
    },
  },
  {
    id: "ferc-order-1920",
    title: "FERC Order Nos. 1920 / 1920-A / 1920-B — Long-Term Transmission Planning",
    jurisdiction: "Federal",
    region: "United States",
    policyType: "Transmission planning",
    status: "Effective",
    effectiveDate: "2024-05-13",
    agency: "Federal Energy Regulatory Commission",
    issueAreas: ["Transmission planning", "Cost allocation", "Long-term scenarios"],
    summary:
      "FERC established reforms for long-term regional transmission planning and cost allocation, with later rehearing orders clarifying requirements including state involvement.",
    whyItMatters:
      "Long-horizon transmission planning can affect where future capacity is developed, when grid upgrades become available, and how transmission costs are allocated across beneficiaries.",
    exposure: {
      powerAvailability: "Elevated",
      utilityCost: "Elevated",
      interconnectionTimeline: "Medium",
      siteSelection: "Medium",
      renewableRequirements: "Medium",
      capex: "Elevated",
      opex: "Medium",
      regulatoryUncertainty: "Medium",
    },
    teams: ["Energy", "Site Selection", "Finance", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "Transmission providers must conduct long-term regional transmission planning.",
      "The orders require one or more cost allocation methods for selected long-term regional transmission facilities.",
    ],
    source: {
      label: "FERC explainer: Transmission Planning and Cost Allocation Final Rule",
      url: "https://www.ferc.gov/explainer-transmission-planning-and-cost-allocation-final-rule",
      publishedDate: "2025-04-11",
      sourceType: "Primary",
    },
  },
  {
    id: "virginia-jlarc-data-centers",
    title: "Virginia JLARC Data Centers Study",
    jurisdiction: "Virginia",
    region: "PJM / Virginia",
    policyType: "State policy study",
    status: "Published",
    effectiveDate: "2024-12-09",
    agency: "Joint Legislative Audit and Review Commission",
    issueAreas: ["Load growth", "Generation", "Transmission", "Tax incentives"],
    summary:
      "Virginia's JLARC published a statewide review of data center economic, energy, land-use, and infrastructure impacts, including independent modeling of future electricity demand and grid build requirements.",
    whyItMatters:
      "The study provides an official evidence base for future Virginia policy decisions and highlights the scale of generation and transmission development associated with continued data center load growth.",
    exposure: {
      powerAvailability: "Constrained",
      utilityCost: "Elevated",
      interconnectionTimeline: "Elevated",
      siteSelection: "Elevated",
      renewableRequirements: "Medium",
      capex: "Elevated",
      opex: "Elevated",
      regulatoryUncertainty: "Medium",
    },
    teams: ["Energy", "Site Selection", "Finance", "Sustainability", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "JLARC reports that data center growth is the main driver of its forecast increase in Virginia electricity demand.",
      "The study states that substantial new generation and transmission infrastructure would be needed under modeled demand scenarios.",
    ],
    source: {
      label: "Virginia JLARC: Data Centers in Virginia",
      url: "https://jlarc.virginia.gov/landing-2024-data-centers-in-virginia.asp",
      publishedDate: "2024",
      sourceType: "Primary",
    },
  },
  {
    id: "georgia-psc-large-load-rule",
    title: "Georgia PSC Large-Load Data Center Terms",
    jurisdiction: "Georgia",
    region: "Georgia Power",
    policyType: "Utility tariff / large-load terms",
    status: "Approved",
    effectiveDate: "2025-01-23",
    agency: "Georgia Public Service Commission",
    issueAreas: ["Utility tariffs", "Large loads", "Cost allocation"],
    summary:
      "The Georgia PSC approved a rule allowing Georgia Power to use additional terms and conditions for new customers above 100 MW, including data centers, to address large-load cost and risk allocation.",
    whyItMatters:
      "Very large projects may face negotiated or non-standard service terms that affect commercial commitments, load ramp assumptions, and the economics of site energization.",
    exposure: {
      powerAvailability: "Medium",
      utilityCost: "High",
      interconnectionTimeline: "Medium",
      siteSelection: "Elevated",
      renewableRequirements: "Low",
      capex: "Elevated",
      opex: "High",
      regulatoryUncertainty: "Medium",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The approved rule applies to new customers using more than 100 MW.",
      "The rule allows billing terms and conditions beyond those used for standard customers.",
    ],
    source: {
      label: "Georgia PSC: PSC Approves Rule to Allow New Power Usage Terms for Data Centers",
      url: "https://psc.ga.gov/site/assets/files/8617/media_advisory_data_centers_rule_1-23-2025.pdf",
      publishedDate: "2025-01-23",
      sourceType: "Primary",
    },
  },
  {
    id: "ohio-aep-data-center-tariff",
    title: "AEP Ohio Data Center Tariff",
    jurisdiction: "Ohio",
    region: "AEP Ohio / PJM",
    policyType: "Utility tariff",
    status: "Effective",
    effectiveDate: "2025-07-23",
    agency: "Public Utilities Commission of Ohio",
    issueAreas: ["Utility tariffs", "Contract capacity", "Large-load queue"],
    summary:
      "PUCO approved a data-center-specific tariff for AEP Ohio. The tariff applies to qualifying large data centers and includes minimum billing commitments, financial requirements, and provisions addressing unused contracted capacity.",
    whyItMatters:
      "The tariff directly changes the commercial risk of reserving large blocks of capacity in central Ohio, making load forecasts, ramp schedules, and exit scenarios material to site economics.",
    exposure: {
      powerAvailability: "Medium",
      utilityCost: "High",
      interconnectionTimeline: "Elevated",
      siteSelection: "High",
      renewableRequirements: "Low",
      capex: "Elevated",
      opex: "High",
      regulatoryUncertainty: "Low",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations"],
    recommendedAction: "Engage",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "PUCO ordered AEP Ohio to implement a data-center-specific tariff in July 2025.",
      "AEP Ohio states that the tariff requires minimum billing tied to contracted capacity and includes financial and exit provisions.",
    ],
    source: {
      label: "PUCO: AEP Ohio data center specific tariff order",
      url: "https://content.govdelivery.com/accounts/OHPUC/bulletins/3e8bb79",
      publishedDate: "2025-07-09",
      sourceType: "Primary",
    },
  },
  {
    id: "texas-sb6-large-loads",
    title: "Texas SB 6 — Large-Load Planning and Interconnection",
    jurisdiction: "Texas",
    region: "ERCOT",
    policyType: "State legislation",
    status: "Effective",
    effectiveDate: "2025-06-20",
    agency: "Texas Legislature / Public Utility Commission of Texas",
    issueAreas: ["Large-load interconnection", "Transmission cost", "Reliability", "Load forecasting"],
    summary:
      "Texas SB 6 established a framework for large-load interconnection standards in ERCOT, including transmission cost recovery, screening and financial requirements, load forecasting provisions, and reliability-related obligations.",
    whyItMatters:
      "Large data center projects in ERCOT can face new evidence, financial, study, and operating requirements before and after interconnection, which can affect development sequencing and service assumptions.",
    exposure: {
      powerAvailability: "Variable",
      utilityCost: "Elevated",
      interconnectionTimeline: "Elevated",
      siteSelection: "Elevated",
      renewableRequirements: "Low",
      capex: "Elevated",
      opex: "Medium",
      regulatoryUncertainty: "Medium",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "SB 6 took effect June 20, 2025 and directs PUCT to establish standards for interconnecting large loads in ERCOT.",
      "The enrolled bill establishes a 75 MW threshold unless PUCT determines a lower threshold is necessary and includes screening, site-control, financial, and reliability provisions.",
    ],
    source: {
      label: "Texas Legislature: SB 6 enrolled bill summary",
      url: "https://capitol.texas.gov/billlookup/BillSummary.aspx?Bill=SB6&LegSess=89R",
      publishedDate: "2025",
      sourceType: "Primary",
    },
  },
  {
    id: "oregon-hb3546",
    title: "Oregon HB 3546 — Large Energy Use Facility Rate Class",
    jurisdiction: "Oregon",
    region: "Oregon IOUs",
    policyType: "State legislation / utility tariff",
    status: "Effective",
    effectiveDate: "2025-06-16",
    agency: "Oregon Legislative Assembly / Oregon Public Utility Commission",
    issueAreas: ["Utility tariffs", "Large loads", "Cost allocation", "Service contracts"],
    summary:
      "Oregon HB 3546 directs the PUC to establish a service classification for large energy use facilities and requires tariff and contract structures intended to allocate service costs and risks to that class.",
    whyItMatters:
      "Large computing facilities meeting the statutory threshold can face a distinct tariff and contracting framework, making long-term power commitments part of development economics.",
    exposure: {
      powerAvailability: "Medium",
      utilityCost: "High",
      interconnectionTimeline: "Medium",
      siteSelection: "Elevated",
      renewableRequirements: "Low",
      capex: "Medium",
      opex: "High",
      regulatoryUncertainty: "Elevated",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "HB 3546 directs Oregon PUC to establish a classification of service for large energy use facilities.",
      "The measure requires tariff schedules to allocate the costs of serving the class and mitigate risks to other retail electricity customer classes.",
    ],
    source: {
      label: "Oregon Legislative Information System: HB 3546",
      url: "https://olis.oregonlegislature.gov/liz/2025R1/Measures/Overview/HB3546",
      publishedDate: "2025",
      sourceType: "Primary",
    },
  },
  {
    id: "illinois-data-center-incentive",
    title: "Illinois Data Center Incentive Program Intake Change",
    jurisdiction: "Illinois",
    region: "Illinois",
    policyType: "Tax incentive",
    status: "Program intake paused",
    effectiveDate: "2026-07-01",
    agency: "Illinois Department of Commerce and Economic Opportunity",
    issueAreas: ["Tax incentives", "Site selection", "Capital investment"],
    summary:
      "Illinois DCEO states that, under a June 2026 directive, it stopped processing applications for the state data center incentive program as of July 1, 2026.",
    whyItMatters:
      "Projects evaluating Illinois should not assume the historical incentive application pathway remains available. Incentive assumptions should be revalidated before they are included in site-selection economics.",
    exposure: {
      powerAvailability: "Low",
      utilityCost: "Low",
      interconnectionTimeline: "Low",
      siteSelection: "High",
      renewableRequirements: "Low",
      capex: "High",
      opex: "Medium",
      regulatoryUncertainty: "Elevated",
    },
    teams: ["Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Finance",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "DCEO states that it will no longer process applications for the data center incentive program as of July 1, 2026.",
      "The program historically provided qualifying projects with specified state and local tax exemptions and certain construction-workforce credits.",
    ],
    source: {
      label: "Illinois DCEO: Data Center Investment Tax Exemptions and Credits",
      url: "https://dceo.illinois.gov/expandrelocate/incentives/datacenters.html",
      publishedDate: "2026",
      sourceType: "Primary",
    },
  },
  {
    id: "pennsylvania-grid-requirements",
    title: "Pennsylvania GRID Requirements for Data Center Development",
    jurisdiction: "Pennsylvania",
    region: "Pennsylvania / PJM",
    policyType: "Executive order / permitting",
    status: "Effective",
    effectiveDate: "2026-08-18",
    agency: "Commonwealth of Pennsylvania",
    issueAreas: ["Permitting", "Energy cost responsibility", "Community process", "Environmental requirements"],
    summary:
      "Pennsylvania Executive Order 2026-05 directs state agencies to incorporate GRID requirements into data center permitting and links state support and certain incentive treatment to specified developer commitments.",
    whyItMatters:
      "Project permitting, local approvals, infrastructure-cost commitments, community engagement, and environmental planning are now more tightly connected for new Pennsylvania data center proposals.",
    exposure: {
      powerAvailability: "Elevated",
      utilityCost: "Elevated",
      interconnectionTimeline: "Elevated",
      siteSelection: "High",
      renewableRequirements: "Elevated",
      capex: "High",
      opex: "Medium",
      regulatoryUncertainty: "Elevated",
    },
    teams: ["Energy", "Site Selection", "Construction", "Finance", "Sustainability", "Legal", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "Executive Order 2026-05 was signed August 18, 2026 and directs DEP to incorporate GRID requirements into review of data center proposals.",
      "The requirements address energy affordability, community engagement, workforce and economic development, transparency, and environmental protection.",
    ],
    source: {
      label: "Pennsylvania DCED: GRID Requirements",
      url: "https://dced.pa.gov/business-assistance/data-center-resources/grid-requirements/",
      publishedDate: "2026-08-18",
      sourceType: "Primary",
    },
  },
  {
    id: "arizona-aps-large-load-rate-case",
    title: "Arizona APS Extra High Load Factor Rate Case",
    jurisdiction: "Arizona",
    region: "Arizona Public Service",
    policyType: "Utility rate case",
    status: "Pending",
    effectiveDate: "Expected decision by 2026-12-31",
    agency: "Arizona Corporation Commission",
    issueAreas: ["Large-load tariff", "Utility rates", "Data centers"],
    summary:
      "Arizona regulators are considering changes in APS's rate case that include the Extra High Load Factor class used by large-load customers such as manufacturing facilities and data centers.",
    whyItMatters:
      "Final rate design could change the economics and contract structure for future large loads in APS territory. The record remains pending, so assumptions should be treated as provisional.",
    exposure: {
      powerAvailability: "Variable",
      utilityCost: "High",
      interconnectionTimeline: "Medium",
      siteSelection: "Elevated",
      renewableRequirements: "Low",
      capex: "Medium",
      opex: "High",
      regulatoryUncertainty: "High",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Public Policy",
    dueDate: "2026-12-31",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The APS rate case hearing concluded July 7, 2026.",
      "The Arizona Corporation Commission identifies changes to the Extra High Load Factor class for large-load users, including data centers, as a key issue in the case.",
    ],
    source: {
      label: "Arizona Corporation Commission: What's Next in the APS Rate Case?",
      url: "https://www.azcc.gov/news/home/2026/07/10/what-s-next-in-the-aps-rate-case",
      publishedDate: "2026-07-10",
      sourceType: "Primary",
    },
  },
];

export const marketProfiles: MarketProfile[] = [
  {
    market: "Virginia",
    powerAvailability: "Constrained",
    interconnection: "Elevated",
    tariffRisk: "Medium",
    dataCenterPolicy: "Active",
    cleanEnergy: "Elevated",
    overallExposure: "Elevated",
    basis: "JLARC demand and infrastructure findings; PJM context.",
  },
  {
    market: "Texas",
    powerAvailability: "Variable",
    interconnection: "Elevated",
    tariffRisk: "Elevated",
    dataCenterPolicy: "Active",
    cleanEnergy: "Low",
    overallExposure: "Elevated",
    basis: "SB 6 large-load interconnection, cost and reliability requirements.",
  },
  {
    market: "Georgia",
    powerAvailability: "Medium",
    interconnection: "Medium",
    tariffRisk: "High",
    dataCenterPolicy: "Active",
    cleanEnergy: "Low",
    overallExposure: "Elevated",
    basis: "PSC-approved special terms for new customers above 100 MW.",
  },
  {
    market: "Ohio",
    powerAvailability: "Medium",
    interconnection: "Elevated",
    tariffRisk: "High",
    dataCenterPolicy: "Active",
    cleanEnergy: "Low",
    overallExposure: "High",
    basis: "AEP Ohio data center tariff and large-load contracting requirements.",
  },
  {
    market: "Oregon",
    powerAvailability: "Medium",
    interconnection: "Medium",
    tariffRisk: "High",
    dataCenterPolicy: "Active",
    cleanEnergy: "Medium",
    overallExposure: "Elevated",
    basis: "HB 3546 separate large-energy-use service class and contract framework.",
  },
  {
    market: "Illinois",
    powerAvailability: "Medium",
    interconnection: "Medium",
    tariffRisk: "Medium",
    dataCenterPolicy: "Emerging",
    cleanEnergy: "Medium",
    overallExposure: "Elevated",
    basis: "State data center incentive intake stopped July 1, 2026.",
  },
  {
    market: "Pennsylvania",
    powerAvailability: "Elevated",
    interconnection: "Elevated",
    tariffRisk: "Elevated",
    dataCenterPolicy: "Active",
    cleanEnergy: "Elevated",
    overallExposure: "High",
    basis: "2026 GRID permitting and development requirements.",
  },
  {
    market: "Arizona",
    powerAvailability: "Variable",
    interconnection: "Medium",
    tariffRisk: "High",
    dataCenterPolicy: "Emerging",
    cleanEnergy: "Low",
    overallExposure: "Elevated",
    basis: "Pending APS large-load rate design and ACC large-load proceedings.",
  },
];
