import type { MarketProfile, PolicyRecord } from "@/lib/types";

const reviewed = "2026-09-18";

export const policies: PolicyRecord[] = [
  {
    id: "ferc-order-2023",
    title: "FERC Order No. 2023 — Generator Interconnection Reform",
    jurisdiction: "Federal",
    region: "United States",
    policyType: "Interconnection reform",
    status: "Effective",
    effectiveDate: "2023-11-06",
    agency: "Federal Energy Regulatory Commission",
    issueAreas: ["Generator interconnection", "Transmission", "Queue reform"],
    summary:
      "FERC revised pro forma generator interconnection procedures and agreements, including a first-ready, first-served cluster study process, readiness requirements, and other queue reforms.",
    whyItMatters:
      "Data center power availability can depend on how quickly new generation and network upgrades advance through interconnection processes. The order changes the upstream framework used by public utilities.",
    businessImpact: {
      powerAvailability: "Relevant to the pace at which new generation supporting load growth can reach service.",
      utilityCost: "Network-upgrade allocation and study outcomes can affect upstream project economics.",
      interconnectionTimeline: "Cluster studies, readiness requirements, and queue reforms alter generator-development sequencing.",
      siteSelection: "Markets dependent on significant new generation may be more sensitive to queue performance.",
      renewableRequirements: "No data-center-specific renewable mandate in this record.",
      capex: "Potential indirect effect through network upgrades and generation-development costs.",
      opex: "No direct data-center operating-rate term in this record.",
      regulatoryUncertainty: "Implementation occurs through transmission-provider compliance processes.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The final rule revises pro forma generator interconnection procedures and agreements.",
      "The rule adopts a first-ready, first-served cluster study process and readiness requirements.",
    ],
    claims: [
      {
        id: "ferc-2023-c1",
        text: "Order No. 2023 adopts a first-ready, first-served cluster study process.",
        sourceLabel: "FERC Order No. 2023 fact sheet",
        sourceUrl: "https://www.ferc.gov/news-events/news/fact-sheet-improvements-generator-interconnection-procedures-and-agreements",
      },
      {
        id: "ferc-2023-c2",
        text: "The order adds readiness requirements to the generator interconnection process.",
        sourceLabel: "FERC Order No. 2023 fact sheet",
        sourceUrl: "https://www.ferc.gov/news-events/news/fact-sheet-improvements-generator-interconnection-procedures-and-agreements",
      },
    ],
    source: {
      label: "FERC fact sheet: Improvements to Generator Interconnection Procedures and Agreements",
      url: "https://www.ferc.gov/news-events/news/fact-sheet-improvements-generator-interconnection-procedures-and-agreements",
      publishedDate: "2023-07-27",
      sourceType: "Primary",
    },
  },
  {
    id: "ferc-order-1920",
    title: "FERC Order Nos. 1920 / 1920-A / 1920-B — Long-Term Transmission Planning",
    jurisdiction: "Federal",
    region: "United States",
    policyType: "Transmission planning",
    status: "Effective",
    effectiveDate: "2024-05-13",
    agency: "Federal Energy Regulatory Commission",
    issueAreas: ["Transmission planning", "Cost allocation", "Long-term scenarios"],
    summary:
      "FERC established reforms for long-term regional transmission planning and cost allocation, with later rehearing orders clarifying requirements including state involvement.",
    whyItMatters:
      "Long-horizon transmission planning can affect where future grid capacity is developed, when major upgrades are selected, and how certain transmission costs are allocated.",
    businessImpact: {
      powerAvailability: "Relevant to long-term regional transmission expansion supporting future load.",
      utilityCost: "Cost-allocation methods can influence transmission-related charges borne across beneficiaries.",
      interconnectionTimeline: "Transmission planning can affect availability of network capacity but does not itself set a data-center connection schedule.",
      siteSelection: "Long-term transmission plans can change capacity outlooks across regions.",
      renewableRequirements: "Planning scenarios can account for resource and policy changes but do not create a data-center renewable mandate.",
      capex: "Transmission expansion can alter infrastructure requirements and cost-allocation assumptions.",
      opex: "Potential indirect effect through transmission charges.",
      regulatoryUncertainty: "Regional compliance and implementation remain important to track.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "Transmission providers must conduct long-term regional transmission planning.",
      "The orders require one or more cost allocation methods for selected long-term regional transmission facilities.",
    ],
    claims: [
      {
        id: "ferc-1920-c1",
        text: "The rule requires long-term regional transmission planning.",
        sourceLabel: "FERC transmission planning explainer",
        sourceUrl: "https://www.ferc.gov/explainer-transmission-planning-and-cost-allocation-final-rule",
      },
      {
        id: "ferc-1920-c2",
        text: "The rule addresses cost allocation for selected long-term regional transmission facilities.",
        sourceLabel: "FERC transmission planning explainer",
        sourceUrl: "https://www.ferc.gov/explainer-transmission-planning-and-cost-allocation-final-rule",
      },
    ],
    source: {
      label: "FERC explainer: Transmission Planning and Cost Allocation Final Rule",
      url: "https://www.ferc.gov/explainer-transmission-planning-and-cost-allocation-final-rule",
      publishedDate: "2025-04-11",
      sourceType: "Primary",
    },
  },
  {
    id: "virginia-jlarc-data-centers",
    title: "Virginia JLARC Data Centers Study",
    jurisdiction: "Virginia",
    region: "PJM / Virginia",
    policyType: "State policy study",
    status: "Published",
    effectiveDate: "2024-12-09",
    agency: "Joint Legislative Audit and Review Commission",
    issueAreas: ["Load growth", "Generation", "Transmission", "Tax incentives"],
    summary:
      "Virginia's JLARC published a statewide review of data center economic, energy, land-use, and infrastructure impacts, including independent modeling of future electricity demand and grid build requirements.",
    whyItMatters:
      "The study is an official evidence base for future Virginia policy decisions and documents the scale of generation and transmission development associated with modeled data center load growth.",
    businessImpact: {
      powerAvailability: "JLARC modeling identifies substantial generation and transmission needs under higher demand scenarios.",
      utilityCost: "The study examines system investment and customer-cost implications rather than setting a specific tariff.",
      interconnectionTimeline: "Large infrastructure requirements can influence development sequencing.",
      siteSelection: "Virginia remains a major data center market, making documented infrastructure needs relevant to site diligence.",
      renewableRequirements: "The study considers Virginia energy-policy context but does not itself impose a new procurement requirement.",
      capex: "Potential exposure through required generation and transmission buildout.",
      opex: "Potential exposure through electricity-system costs, subject to future rate design.",
      regulatoryUncertainty: "The study can inform future legislative and regulatory action but is not itself a binding tariff.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Sustainability", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "JLARC reports that data center growth is the main driver of its forecast increase in Virginia electricity demand.",
      "The study states that substantial new generation and transmission infrastructure would be needed under modeled demand scenarios.",
    ],
    claims: [
      {
        id: "va-jlarc-c1",
        text: "JLARC identifies data center growth as a main driver of forecast electricity-demand growth.",
        sourceLabel: "Virginia JLARC: Data Centers in Virginia",
        sourceUrl: "https://jlarc.virginia.gov/landing-2024-data-centers-in-virginia.asp",
      },
      {
        id: "va-jlarc-c2",
        text: "JLARC's modeled scenarios require substantial generation and transmission additions.",
        sourceLabel: "Virginia JLARC: Data Centers in Virginia",
        sourceUrl: "https://jlarc.virginia.gov/landing-2024-data-centers-in-virginia.asp",
      },
    ],
    source: {
      label: "Virginia JLARC: Data Centers in Virginia",
      url: "https://jlarc.virginia.gov/landing-2024-data-centers-in-virginia.asp",
      publishedDate: "2024",
      sourceType: "Primary",
    },
  },
  {
    id: "georgia-psc-large-load-rule",
    title: "Georgia PSC Large-Load Data Center Terms",
    jurisdiction: "Georgia",
    region: "Georgia Power",
    policyType: "Utility tariff / large-load terms",
    status: "Approved",
    effectiveDate: "2025-01-23",
    agency: "Georgia Public Service Commission",
    issueAreas: ["Utility tariffs", "Large loads", "Cost allocation"],
    summary:
      "The Georgia PSC approved a rule allowing Georgia Power to use additional terms and conditions for new customers above 100 MW, including data centers, to address large-load cost and risk allocation.",
    whyItMatters:
      "Very large projects may face negotiated or non-standard service terms that affect commercial commitments, load ramp assumptions, and the economics of site energization.",
    businessImpact: {
      powerAvailability: "Large new loads remain subject to utility system capability and service arrangements.",
      utilityCost: "Projects above the threshold can face additional billing terms and cost-responsibility provisions.",
      interconnectionTimeline: "Additional commercial and infrastructure terms can become part of the connection process.",
      siteSelection: "Service-term diligence is required for projects above 100 MW.",
      renewableRequirements: "No data-center-specific renewable requirement in this record.",
      capex: "Potential project obligations for facilities and financial security.",
      opex: "Additional billing terms can affect recurring power-cost assumptions.",
      regulatoryUncertainty: "Approved framework exists; project-specific terms still require diligence.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The approved rule applies to new customers using more than 100 MW.",
      "The rule allows billing terms and conditions beyond those used for standard customers.",
    ],
    claims: [
      {
        id: "ga-c1",
        text: "The Georgia PSC rule applies to new customers above 100 MW.",
        sourceLabel: "Georgia PSC data center rule advisory",
        sourceUrl: "https://psc.ga.gov/site/assets/files/8617/media_advisory_data_centers_rule_1-23-2025.pdf",
      },
      {
        id: "ga-c2",
        text: "The rule authorizes additional terms and conditions for qualifying large-load customers.",
        sourceLabel: "Georgia PSC data center rule advisory",
        sourceUrl: "https://psc.ga.gov/site/assets/files/8617/media_advisory_data_centers_rule_1-23-2025.pdf",
      },
    ],
    source: {
      label: "Georgia PSC: PSC Approves Rule to Allow New Power Usage Terms for Data Centers",
      url: "https://psc.ga.gov/site/assets/files/8617/media_advisory_data_centers_rule_1-23-2025.pdf",
      publishedDate: "2025-01-23",
      sourceType: "Primary",
    },
  },
  {
    id: "ohio-aep-data-center-tariff",
    title: "AEP Ohio Data Center Tariff",
    jurisdiction: "Ohio",
    region: "AEP Ohio / PJM",
    policyType: "Utility tariff",
    status: "Effective",
    effectiveDate: "2025-07-23",
    agency: "Public Utilities Commission of Ohio",
    issueAreas: ["Utility tariffs", "Contract capacity", "Large-load queue"],
    summary:
      "PUCO approved a data-center-specific tariff for AEP Ohio that includes minimum billing commitments, financial requirements, and provisions addressing unused contracted capacity.",
    whyItMatters:
      "The tariff changes the commercial framework for reserving large blocks of capacity in central Ohio, making load forecasts, ramp schedules, and exit scenarios material to project economics.",
    businessImpact: {
      powerAvailability: "Capacity reservation is linked to tariff and contracting requirements.",
      utilityCost: "Minimum billing tied to contracted capacity affects power-cost assumptions.",
      interconnectionTimeline: "Large-load queue and service commitments become part of development sequencing.",
      siteSelection: "Ohio projects need tariff-specific commercial diligence before capacity is reserved.",
      renewableRequirements: "No data-center-specific renewable requirement in this record.",
      capex: "Financial security and infrastructure obligations can affect upfront commitments.",
      opex: "Minimum billing and contracted-capacity provisions affect recurring electricity cost.",
      regulatoryUncertainty: "Approved tariff provides a defined framework, subject to future commission action.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations"],
    recommendedAction: "Engage",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "PUCO ordered AEP Ohio to implement a data-center-specific tariff in July 2025.",
      "The tariff includes minimum billing tied to contracted capacity and financial and exit provisions.",
    ],
    claims: [
      {
        id: "oh-c1",
        text: "PUCO approved a data-center-specific tariff for AEP Ohio.",
        sourceLabel: "PUCO data center tariff order summary",
        sourceUrl: "https://content.govdelivery.com/accounts/OHPUC/bulletins/3e8bb79",
      },
      {
        id: "oh-c2",
        text: "The approved framework includes minimum billing and financial requirements.",
        sourceLabel: "PUCO data center tariff order summary",
        sourceUrl: "https://content.govdelivery.com/accounts/OHPUC/bulletins/3e8bb79",
      },
    ],
    source: {
      label: "PUCO: AEP Ohio data center specific tariff order",
      url: "https://content.govdelivery.com/accounts/OHPUC/bulletins/3e8bb79",
      publishedDate: "2025-07-09",
      sourceType: "Primary",
    },
  },
  {
    id: "texas-sb6-large-loads",
    title: "Texas SB 6 — Large-Load Planning and Interconnection",
    jurisdiction: "Texas",
    region: "ERCOT",
    policyType: "State legislation",
    status: "Effective",
    effectiveDate: "2025-06-20",
    agency: "Texas Legislature / Public Utility Commission of Texas",
    issueAreas: ["Large-load interconnection", "Transmission cost", "Reliability", "Load forecasting"],
    summary:
      "Texas SB 6 established a framework for large-load interconnection standards in ERCOT, including transmission cost recovery, screening and financial requirements, load forecasting provisions, and reliability-related obligations.",
    whyItMatters:
      "Large data center projects in ERCOT can face evidence, financial, study, and operating requirements before and after connection, affecting development sequencing and service assumptions.",
    businessImpact: {
      powerAvailability: "Large-load service depends on ERCOT and utility screening, studies, and system capability.",
      utilityCost: "The framework addresses transmission cost responsibility and financial commitments.",
      interconnectionTimeline: "Large-load standards add defined screening and study steps.",
      siteSelection: "Project feasibility depends on utility territory, system capability, and compliance with large-load requirements.",
      renewableRequirements: "No data-center-specific renewable procurement mandate in this record.",
      capex: "Transmission-related and financial requirements can affect upfront project commitments.",
      opex: "Reliability and service requirements can affect operational planning.",
      regulatoryUncertainty: "PUCT implementation details and utility processes remain relevant to track.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "SB 6 took effect June 20, 2025 and directs PUCT to establish standards for interconnecting large loads in ERCOT.",
      "The enrolled bill includes screening, site-control, financial, and reliability provisions.",
    ],
    claims: [
      {
        id: "tx-c1",
        text: "SB 6 directs PUCT to establish standards for interconnecting large loads in ERCOT.",
        sourceLabel: "Texas Legislature SB 6 summary",
        sourceUrl: "https://capitol.texas.gov/billlookup/BillSummary.aspx?Bill=SB6&LegSess=89R",
      },
      {
        id: "tx-c2",
        text: "The statute includes financial and reliability-related provisions for large loads.",
        sourceLabel: "Texas Legislature SB 6 summary",
        sourceUrl: "https://capitol.texas.gov/billlookup/BillSummary.aspx?Bill=SB6&LegSess=89R",
      },
    ],
    source: {
      label: "Texas Legislature: SB 6 enrolled bill summary",
      url: "https://capitol.texas.gov/billlookup/BillSummary.aspx?Bill=SB6&LegSess=89R",
      publishedDate: "2025",
      sourceType: "Primary",
    },
  },
  {
    id: "oregon-hb3546",
    title: "Oregon HB 3546 — Large Energy Use Facility Rate Class",
    jurisdiction: "Oregon",
    region: "Oregon IOUs",
    policyType: "State legislation / utility tariff",
    status: "Effective",
    effectiveDate: "2025-06-16",
    agency: "Oregon Legislative Assembly / Oregon Public Utility Commission",
    issueAreas: ["Utility tariffs", "Large loads", "Cost allocation", "Service contracts"],
    summary:
      "Oregon HB 3546 directs the PUC to establish a service classification for large energy use facilities and requires tariff and contract structures addressing service costs and risk allocation.",
    whyItMatters:
      "Large computing facilities meeting the statutory threshold can face a distinct tariff and contracting framework, making long-term power commitments part of development economics.",
    businessImpact: {
      powerAvailability: "Service remains utility-specific, with a distinct framework for qualifying large energy users.",
      utilityCost: "The statute directs cost allocation to the large-energy-use class.",
      interconnectionTimeline: "Contracting and utility review can affect service sequencing.",
      siteSelection: "Qualifying projects need Oregon-specific tariff diligence.",
      renewableRequirements: "No project-specific renewable procurement term is set in this tracker record.",
      capex: "Potential financial and infrastructure commitments under implementing tariffs.",
      opex: "Separate rate-class treatment can affect recurring electricity cost.",
      regulatoryUncertainty: "PUC implementation and utility tariff details are the key follow-on items.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "HB 3546 directs Oregon PUC to establish a classification of service for large energy use facilities.",
      "The measure requires tariff schedules addressing the costs of serving the class.",
    ],
    claims: [
      {
        id: "or-c1",
        text: "HB 3546 directs the Oregon PUC to establish a large energy use facility service classification.",
        sourceLabel: "Oregon Legislature HB 3546",
        sourceUrl: "https://olis.oregonlegislature.gov/liz/2025R1/Measures/Overview/HB3546",
      },
      {
        id: "or-c2",
        text: "The measure requires tariff treatment for costs associated with serving the class.",
        sourceLabel: "Oregon Legislature HB 3546",
        sourceUrl: "https://olis.oregonlegislature.gov/liz/2025R1/Measures/Overview/HB3546",
      },
    ],
    source: {
      label: "Oregon Legislative Information System: HB 3546",
      url: "https://olis.oregonlegislature.gov/liz/2025R1/Measures/Overview/HB3546",
      publishedDate: "2025",
      sourceType: "Primary",
    },
  },
  {
    id: "illinois-data-center-incentive",
    title: "Illinois Data Center Incentive Program Intake Change",
    jurisdiction: "Illinois",
    region: "Illinois",
    policyType: "Tax incentive",
    status: "Program intake paused",
    effectiveDate: "2026-07-01",
    agency: "Illinois Department of Commerce and Economic Opportunity",
    issueAreas: ["Tax incentives", "Site selection", "Capital investment"],
    summary:
      "Illinois DCEO states that, under a June 2026 directive, it stopped processing applications for the state data center incentive program as of July 1, 2026.",
    whyItMatters:
      "Projects evaluating Illinois should not assume the historical incentive application pathway remains available. Incentive assumptions need current confirmation before inclusion in site-selection economics.",
    businessImpact: {
      powerAvailability: "No direct change to electric service in this record.",
      utilityCost: "No direct tariff change in this record.",
      interconnectionTimeline: "No direct interconnection change in this record.",
      siteSelection: "Incentive availability assumptions need to be revalidated for Illinois projects.",
      renewableRequirements: "No new clean-energy requirement in this record.",
      capex: "Loss or delay of anticipated tax treatment can change project capital economics.",
      opex: "Tax treatment can affect total operating economics depending on project structure.",
      regulatoryUncertainty: "Program intake status should be checked before relying on prior incentive rules.",
    },
    teams: ["Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Finance",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "DCEO states that it will no longer process applications for the data center incentive program as of July 1, 2026.",
      "The program historically provided qualifying projects with specified state and local tax exemptions and certain construction-workforce credits.",
    ],
    claims: [
      {
        id: "il-c1",
        text: "Illinois DCEO stopped processing applications for the data center incentive program as of July 1, 2026.",
        sourceLabel: "Illinois DCEO data center incentive page",
        sourceUrl: "https://dceo.illinois.gov/expandrelocate/incentives/datacenters.html",
      },
      {
        id: "il-c2",
        text: "The program historically offered specified tax exemptions and credits to qualifying projects.",
        sourceLabel: "Illinois DCEO data center incentive page",
        sourceUrl: "https://dceo.illinois.gov/expandrelocate/incentives/datacenters.html",
      },
    ],
    source: {
      label: "Illinois DCEO: Data Center Investment Tax Exemptions and Credits",
      url: "https://dceo.illinois.gov/expandrelocate/incentives/datacenters.html",
      publishedDate: "2026",
      sourceType: "Primary",
    },
  },
  {
    id: "pennsylvania-grid-requirements",
    title: "Pennsylvania GRID Requirements for Data Center Development",
    jurisdiction: "Pennsylvania",
    region: "Pennsylvania / PJM",
    policyType: "Executive order / permitting",
    status: "Effective",
    effectiveDate: "2026-08-18",
    agency: "Commonwealth of Pennsylvania",
    issueAreas: ["Permitting", "Energy cost responsibility", "Community process", "Environmental requirements"],
    summary:
      "Pennsylvania Executive Order 2026-05 directs state agencies to incorporate GRID requirements into data center permitting and links state support and certain incentive treatment to specified developer commitments.",
    whyItMatters:
      "Project permitting, local approvals, infrastructure-cost commitments, community engagement, and environmental planning are more tightly connected for new Pennsylvania data center proposals.",
    businessImpact: {
      powerAvailability: "Energy-responsibility commitments become part of project planning.",
      utilityCost: "Projects need to account for commitments associated with energy infrastructure and service.",
      interconnectionTimeline: "Permitting and infrastructure commitments can affect development sequencing.",
      siteSelection: "GRID requirements add Pennsylvania-specific diligence for proposed sites.",
      renewableRequirements: "Environmental and energy commitments are part of the framework and require project-specific review.",
      capex: "Developer commitments can affect infrastructure and mitigation costs.",
      opex: "Operational commitments may affect ongoing compliance and energy planning.",
      regulatoryUncertainty: "Implementation across agencies and projects should be monitored.",
    },
    teams: ["Energy", "Site Selection", "Construction", "Finance", "Sustainability", "Legal", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "Executive Order 2026-05 was signed August 18, 2026 and directs DEP to incorporate GRID requirements into review of data center proposals.",
      "The requirements address energy affordability, community engagement, workforce and economic development, transparency, and environmental protection.",
    ],
    claims: [
      {
        id: "pa-c1",
        text: "Pennsylvania's GRID requirements apply to state review of data center proposals.",
        sourceLabel: "Pennsylvania DCED GRID Requirements",
        sourceUrl: "https://dced.pa.gov/business-assistance/data-center-resources/grid-requirements/",
      },
      {
        id: "pa-c2",
        text: "The framework addresses energy, community, workforce, transparency, and environmental commitments.",
        sourceLabel: "Pennsylvania DCED GRID Requirements",
        sourceUrl: "https://dced.pa.gov/business-assistance/data-center-resources/grid-requirements/",
      },
    ],
    source: {
      label: "Pennsylvania DCED: GRID Requirements",
      url: "https://dced.pa.gov/business-assistance/data-center-resources/grid-requirements/",
      publishedDate: "2026-08-18",
      sourceType: "Primary",
    },
  },
  {
    id: "arizona-aps-large-load-rate-case",
    title: "Arizona APS Extra High Load Factor Rate Case",
    jurisdiction: "Arizona",
    region: "Arizona Public Service",
    policyType: "Utility rate case",
    status: "Pending",
    effectiveDate: "Expected decision by 2026-12-31",
    agency: "Arizona Corporation Commission",
    issueAreas: ["Large-load tariff", "Utility rates", "Data centers"],
    summary:
      "Arizona regulators are considering changes in APS's rate case that include the Extra High Load Factor class used by large-load customers such as manufacturing facilities and data centers.",
    whyItMatters:
      "Final rate design could change the economics and contract structure for future large loads in APS territory. The record remains pending, so assumptions should be treated as provisional.",
    businessImpact: {
      powerAvailability: "No final change in this record; system capability remains project-specific.",
      utilityCost: "Pending rate design may alter large-load pricing and contract terms.",
      interconnectionTimeline: "Rate-case outcome may affect commercial readiness more than the physical study process.",
      siteSelection: "APS-territory economics should be modeled with provisional assumptions until a final order.",
      renewableRequirements: "No final data-center-specific clean-energy requirement in this record.",
      capex: "Potential changes to service and financial requirements remain under review.",
      opex: "Final rate design may affect recurring power costs.",
      regulatoryUncertainty: "The proceeding remains pending.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Monitor",
    owner: "Public Policy",
    dueDate: "2026-12-31",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The APS rate case hearing concluded July 7, 2026.",
      "The Arizona Corporation Commission identifies changes to the Extra High Load Factor class for large-load users, including data centers, as a key issue in the case.",
    ],
    claims: [
      {
        id: "az-c1",
        text: "The APS rate case includes the Extra High Load Factor class used by large-load customers including data centers.",
        sourceLabel: "Arizona Corporation Commission APS rate case update",
        sourceUrl: "https://www.azcc.gov/news/home/2026/07/10/what-s-next-in-the-aps-rate-case",
      },
      {
        id: "az-c2",
        text: "The APS rate case hearing concluded in July 2026 and a final decision was still pending.",
        sourceLabel: "Arizona Corporation Commission APS rate case update",
        sourceUrl: "https://www.azcc.gov/news/home/2026/07/10/what-s-next-in-the-aps-rate-case",
      },
    ],
    source: {
      label: "Arizona Corporation Commission: What's Next in the APS Rate Case?",
      url: "https://www.azcc.gov/news/home/2026/07/10/what-s-next-in-the-aps-rate-case",
      publishedDate: "2026-07-10",
      sourceType: "Primary",
    },
  },
  {
    id: "california-pge-rule-30",
    title: "California CPUC Interim PG&E Electric Rule 30",
    jurisdiction: "California",
    region: "PG&E / CAISO",
    policyType: "Transmission-level service rule",
    status: "Approved",
    effectiveDate: "2025-07-24",
    agency: "California Public Utilities Commission",
    issueAreas: ["Large-load connections", "Transmission service", "Upfront infrastructure funding"],
    summary:
      "The CPUC partially approved PG&E's proposed Electric Rule 30 for interim implementation, creating a transmission-level service pathway for high-energy users including data centers.",
    whyItMatters:
      "The rule provides a more standardized pathway for transmission-level connections while requiring participating applicants to fund necessary transmission infrastructure work upfront during the interim period.",
    businessImpact: {
      powerAvailability: "Creates an interim transmission-level service pathway for qualifying large customers in PG&E territory.",
      utilityCost: "Applicants using the interim pathway agree to pay for necessary transmission infrastructure work upfront; refund treatment is subject to future CPUC action.",
      interconnectionTimeline: "The CPUC describes the rule as intended to streamline and accelerate transmission-level grid connections.",
      siteSelection: "PG&E-territory sites can evaluate a defined large-load connection pathway rather than purely case-by-case handling.",
      renewableRequirements: "No data-center-specific renewable procurement obligation is created by the interim rule.",
      capex: "Upfront transmission-infrastructure funding can materially affect project cash timing.",
      opex: "The interim rule is primarily a connection framework rather than an operating-energy rate.",
      regulatoryUncertainty: "Refund terms and final treatment remain subject to future CPUC decision.",
    },
    teams: ["Energy", "Site Selection", "Construction", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The CPUC partially approved PG&E Electric Rule 30 for interim implementation.",
      "The interim rule is available to applicants that agree to pay for necessary transmission infrastructure work upfront.",
    ],
    claims: [
      {
        id: "ca-c1",
        text: "The CPUC approved interim implementation of PG&E Electric Rule 30 for high-energy users including data centers.",
        sourceLabel: "CPUC Rule 30 announcement",
        sourceUrl: "https://www.cpuc.ca.gov/news-and-updates/all-news/cpuc-streamlines-electric-grid-connections-for-high-energy-users-like-data-centers-and-ev-chargers",
      },
      {
        id: "ca-c2",
        text: "Applicants using the interim rule must pay for necessary transmission infrastructure work upfront.",
        sourceLabel: "CPUC Rule 30 announcement",
        sourceUrl: "https://www.cpuc.ca.gov/news-and-updates/all-news/cpuc-streamlines-electric-grid-connections-for-high-energy-users-like-data-centers-and-ev-chargers",
      },
    ],
    versionHistory: [
      {
        label: "PG&E proposal",
        date: "2024-11-07",
        source: {
          label: "CPUC proceeding description",
          url: "https://www.cpuc.ca.gov/news-and-updates/all-news/cpuc-streamlines-electric-grid-connections-for-high-energy-users-like-data-centers-and-ev-chargers",
        },
        changes: [
          "PG&E proposed a new Electric Rule 30 to standardize transmission-level service for large customers.",
          "The proposal sought to replace case-by-case handling with a defined rule framework.",
        ],
      },
      {
        label: "CPUC interim approval",
        date: "2025-07-24",
        source: {
          label: "CPUC Rule 30 announcement",
          url: "https://www.cpuc.ca.gov/news-and-updates/all-news/cpuc-streamlines-electric-grid-connections-for-high-energy-users-like-data-centers-and-ev-chargers",
        },
        changes: [
          "CPUC partially approved Rule 30 for interim implementation.",
          "Interim applicants must fund necessary transmission infrastructure work upfront.",
          "Refund terms are deferred to a future CPUC decision.",
        ],
      },
    ],
    source: {
      label: "CPUC: Streamlines Electric Grid Connections for High-Energy Users",
      url: "https://www.cpuc.ca.gov/news-and-updates/all-news/cpuc-streamlines-electric-grid-connections-for-high-energy-users-like-data-centers-and-ev-chargers",
      publishedDate: "2025-07-24",
      sourceType: "Primary",
    },
  },
  {
    id: "washington-large-load-docket",
    title: "Washington UTC Emerging Large Electric Loads Docket UE-260162",
    jurisdiction: "Washington",
    region: "Washington investor-owned utilities",
    policyType: "PUC policy proceeding",
    status: "Open proceeding",
    effectiveDate: "2026-07-28",
    agency: "Washington Utilities and Transportation Commission",
    issueAreas: ["Large-load rates", "Cost sharing", "Interconnection", "Load flexibility"],
    summary:
      "Washington UTC is developing policy for emerging large electric loads, including data centers, through Docket UE-260162 and 2026 technical workshops.",
    whyItMatters:
      "The proceeding is examining power rates, cost sharing, interconnection conditions, energy flexibility, and customer protections that can shape future service terms for large loads.",
    businessImpact: {
      powerAvailability: "Future policy may influence how investor-owned utilities assess and serve major new loads.",
      utilityCost: "Rate design and cost sharing are explicit topics in the docket.",
      interconnectionTimeline: "Interconnection conditions are under active review.",
      siteSelection: "Washington projects should treat future IOU large-load terms as an active diligence item.",
      renewableRequirements: "Clean-energy implications may intersect with state policy, but no final new requirement is established in this docket record.",
      capex: "Future cost-sharing rules may affect customer-funded infrastructure.",
      opex: "Future rate structures could alter recurring service costs.",
      regulatoryUncertainty: "The policy process remains open.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy", "Operations"],
    recommendedAction: "Monitor",
    owner: "Public Policy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "UTC Docket UE-260162 addresses emerging large electric loads including data centers.",
      "The 2026 workshop agenda includes power rates, cost sharing, interconnection conditions, energy flexibility, and customer protections.",
    ],
    claims: [
      {
        id: "wa-c1",
        text: "Washington UTC is considering policy for emerging large electric loads including data centers.",
        sourceLabel: "Washington UTC large-load workshop advisory",
        sourceUrl: "https://www.utc.wa.gov/news/2026/media-advisory-public-invited-join-utc-workshop-emerging-large-electric-loads",
      },
      {
        id: "wa-c2",
        text: "The UTC proceeding is considering rates, cost sharing, interconnection conditions, flexibility, and customer protections.",
        sourceLabel: "Washington UTC large-load workshop advisory",
        sourceUrl: "https://www.utc.wa.gov/news/2026/media-advisory-public-invited-join-utc-workshop-emerging-large-electric-loads",
      },
    ],
    source: {
      label: "Washington UTC: Workshop on emerging large electric loads",
      url: "https://www.utc.wa.gov/news/2026/media-advisory-public-invited-join-utc-workshop-emerging-large-electric-loads",
      publishedDate: "2026-07-28",
      sourceType: "Primary",
    },
  },
  {
    id: "wisconsin-we-energies-vlc",
    title: "Wisconsin We Energies Very Large Customer Tariff",
    jurisdiction: "Wisconsin",
    region: "We Energies",
    policyType: "Utility tariff",
    status: "Approved",
    effectiveDate: "2026-04-24",
    agency: "Public Service Commission of Wisconsin",
    issueAreas: ["Large-load tariff", "Contract term", "Financial safeguards", "Transparency"],
    summary:
      "The Wisconsin PSC approved a revised Very Large Customer tariff for We Energies after reviewing the utility's proposal for large data center customers.",
    whyItMatters:
      "The tariff establishes standardized service expectations for very large customers, including contract-term and eligibility provisions that affect large-project commercial structuring.",
    businessImpact: {
      powerAvailability: "Very large customers receive service under a dedicated tariff framework.",
      utilityCost: "Tariff terms govern cost recovery and customer financial obligations.",
      interconnectionTimeline: "Commercial readiness must align with the utility's service and infrastructure process.",
      siteSelection: "We Energies territory now has a dedicated large-load tariff to review during site diligence.",
      renewableRequirements: "The tariff decision is primarily about service and cost allocation rather than a universal renewable mandate.",
      capex: "Financial safeguards and long-term commitments affect project structuring.",
      opex: "Tariff charges and minimum obligations affect recurring electricity economics.",
      regulatoryUncertainty: "Approved tariff provides a defined framework; implementation reporting remains relevant.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Public Policy"],
    recommendedAction: "Analyze",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The PSC approved the We Energies Very Large Customer tariff in April 2026.",
      "The Commission set a 15-year minimum initial term and lowered the tariff eligibility threshold from 500 MW to 100 MW.",
    ],
    claims: [
      {
        id: "wi-c1",
        text: "Wisconsin PSC approved We Energies' Very Large Customer tariff in April 2026.",
        sourceLabel: "Wisconsin PSC tariff announcement",
        sourceUrl: "https://psc.wi.gov/Documents/PressReleases/04.24.2026PressRelease.PDF",
      },
      {
        id: "wi-c2",
        text: "The Commission set a 15-year minimum initial term and a 100 MW eligibility threshold.",
        sourceLabel: "Wisconsin PSC tariff announcement",
        sourceUrl: "https://psc.wi.gov/Documents/PressReleases/04.24.2026PressRelease.PDF",
      },
    ],
    source: {
      label: "Wisconsin PSC: We Energies Data Center Tariff Decision",
      url: "https://psc.wi.gov/Documents/PressReleases/04.24.2026PressRelease.PDF",
      publishedDate: "2026-04-24",
      sourceType: "Primary",
    },
  },
  {
    id: "michigan-consumers-large-load",
    title: "Michigan Consumers Energy Data Center Service Terms",
    jurisdiction: "Michigan",
    region: "Consumers Energy",
    policyType: "Utility tariff / service terms",
    status: "Approved",
    effectiveDate: "2025-11-06",
    agency: "Michigan Public Service Commission",
    issueAreas: ["Large-load tariff", "Contract capacity", "Exit fees", "Financial security"],
    summary:
      "The Michigan PSC approved amendments to Consumers Energy's Rate GPD establishing service terms for data centers and other very large customers.",
    whyItMatters:
      "The approved terms define thresholds, contract duration, minimum billing, ramp-up, exit, collateral, and project-study requirements for very large electric users.",
    businessImpact: {
      powerAvailability: "Prospective large-load customers must progress through utility studies and project-specific service review.",
      utilityCost: "Minimum billing, exit-fee, and collateral provisions affect project economics.",
      interconnectionTimeline: "Study fees and project-specific commission filings become part of development sequencing.",
      siteSelection: "Consumers Energy territory has explicit service terms for qualifying very large loads.",
      renewableRequirements: "Renewable and clean-energy issues are handled in other relevant Michigan proceedings rather than through this tariff alone.",
      capex: "Study costs, collateral, and project infrastructure affect upfront commitments.",
      opex: "Minimum billing demand and service terms affect recurring cost assumptions.",
      regulatoryUncertainty: "Approved tariff exists, with project-specific filings required for new customers.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations", "Public Policy"],
    recommendedAction: "Engage",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "The tariff applies to customers at or above 100 MW, including qualifying aggregated loads.",
      "The approved terms include a 15-year minimum contract term, minimum billing demand, ramp-up, exit-fee, and collateral provisions.",
    ],
    claims: [
      {
        id: "mi-c1",
        text: "Michigan PSC approved Consumers Energy data center and very-large-customer service terms in November 2025.",
        sourceLabel: "Michigan PSC Consumers Energy large-load decision",
        sourceUrl: "https://www.michigan.gov/mpsc/commission/news-releases/2025/11/06/mpsc-approves-terms-of-service-between-consumers-energy-and-data-centers",
      },
      {
        id: "mi-c2",
        text: "The approved terms include a 100 MW threshold and a 15-year minimum contract term.",
        sourceLabel: "Michigan PSC Consumers Energy large-load decision",
        sourceUrl: "https://www.michigan.gov/mpsc/commission/news-releases/2025/11/06/mpsc-approves-terms-of-service-between-consumers-energy-and-data-centers",
      },
    ],
    source: {
      label: "Michigan PSC: Consumers Energy data center service terms",
      url: "https://www.michigan.gov/mpsc/commission/news-releases/2025/11/06/mpsc-approves-terms-of-service-between-consumers-energy-and-data-centers",
      publishedDate: "2025-11-06",
      sourceType: "Primary",
    },
  },
  {
    id: "florida-fpl-llcs",
    title: "Florida Power & Light Large Load Contract Service Tariffs",
    jurisdiction: "Florida",
    region: "Florida Power & Light",
    policyType: "Utility tariff",
    status: "Approved",
    effectiveDate: "2026-01-01",
    agency: "Florida Public Service Commission",
    issueAreas: ["Large-load tariff", "Generation cost", "Contract demand", "Take-or-pay"],
    summary:
      "The Florida PSC approved FPL Large Load Contract Service tariffs LLCS-1 and LLCS-2 as part of the utility's 2025 settlement, with modifications to threshold and minimum billing terms.",
    whyItMatters:
      "The tariffs establish a dedicated service structure for future high-load customers, including data centers, and link large-load service to incremental generation and contract commitments.",
    businessImpact: {
      powerAvailability: "Large-load service is tied to dedicated LLCS arrangements and system resource planning.",
      utilityCost: "The tariffs include incremental generation and other rate components for qualifying customers.",
      interconnectionTimeline: "Engineering, contracting, and service-agreement steps affect project readiness.",
      siteSelection: "FPL-territory projects at the applicable size and load factor need LLCS-specific economic modeling.",
      renewableRequirements: "No universal data-center renewable procurement mandate is created by the LLCS approval.",
      capex: "Service agreements and infrastructure commitments can affect upfront project planning.",
      opex: "Minimum take-or-pay demand and LLCS rate components directly affect recurring power-cost assumptions.",
      regulatoryUncertainty: "Approved terms are defined, though future rate cases can revise pricing.",
    },
    teams: ["Energy", "Site Selection", "Finance", "Legal", "Operations"],
    recommendedAction: "Analyze",
    owner: "Energy",
    sourceConfidence: "High",
    lastReviewed: reviewed,
    evidence: [
      "FPL originally proposed LLCS tariffs for new or incremental load of 25 MW or greater with load factor of 85 percent or greater.",
      "The approved settlement modified applicability to 50 MW or greater and set a 70 percent minimum take-or-pay demand charge.",
    ],
    claims: [
      {
        id: "fl-c1",
        text: "The approved FPL LLCS tariffs apply at 50 MW or greater with an 85 percent or higher load factor.",
        sourceLabel: "Florida PSC Order PSC-2026-0022-S-EI",
        sourceUrl: "https://www.psc.state.fl.us/library/filings/2026/01157-2026/01157-2026.pdf",
      },
      {
        id: "fl-c2",
        text: "The settlement set a 70 percent minimum take-or-pay demand charge for the LLCS tariffs.",
        sourceLabel: "Florida PSC Order PSC-2026-0022-S-EI",
        sourceUrl: "https://www.psc.state.fl.us/library/filings/2026/01157-2026/01157-2026.pdf",
      },
    ],
    versionHistory: [
      {
        label: "FPL original filing",
        date: "2025-02-28",
        source: {
          label: "FPL direct testimony in Docket 20250011-EI",
          url: "https://www.psc.state.fl.us/library/filings/2025/01187-2025/01187-2025.pdf",
        },
        changes: [
          "Proposed LLCS-1 and LLCS-2 for projected new or incremental load of 25 MW or more.",
          "Proposed applicability also required a load factor of 85 percent or more.",
        ],
      },
      {
        label: "Approved settlement terms",
        date: "2026-01-01",
        source: {
          label: "Florida PSC Order PSC-2026-0022-S-EI",
          url: "https://www.psc.state.fl.us/library/filings/2026/01157-2026/01157-2026.pdf",
        },
        changes: [
          "Applicability threshold changed to 50 MW or greater.",
          "85 percent load-factor requirement retained.",
          "Minimum take-or-pay demand charge set at 70 percent.",
        ],
      },
    ],
    source: {
      label: "Florida PSC Order PSC-2026-0022-S-EI",
      url: "https://www.psc.state.fl.us/library/filings/2026/01157-2026/01157-2026.pdf",
      publishedDate: "2026",
      sourceType: "Primary",
    },
  },
];

export const marketProfiles: MarketProfile[] = [
  {
    market: "Virginia",
    trackedDevelopment: "JLARC statewide data center study",
    currentStatus: "Published study used as an official policy evidence base",
    powerSignal: "Generation and transmission build requirements are central to the study.",
    interconnectionSignal: "Infrastructure buildout and PJM timing remain material diligence items.",
    tariffCostSignal: "The tracked record is a policy study, not a dedicated large-load tariff.",
    cleanEnergySignal: "State energy-policy context is part of the study.",
    sourceBasis: "Virginia JLARC.",
  },
  {
    market: "Texas",
    trackedDevelopment: "SB 6 large-load framework",
    currentStatus: "Effective; implementation through PUCT and ERCOT processes",
    powerSignal: "Large-load screening and reliability obligations affect service planning.",
    interconnectionSignal: "Large-load connection standards are a core feature.",
    tariffCostSignal: "Transmission cost responsibility and financial requirements are addressed.",
    cleanEnergySignal: "No data-center-specific renewable mandate in the tracked record.",
    sourceBasis: "Texas Legislature SB 6.",
  },
  {
    market: "Georgia",
    trackedDevelopment: "Georgia Power large-load terms",
    currentStatus: "PSC-approved framework for new customers above 100 MW",
    powerSignal: "Service depends on utility system capability and project terms.",
    interconnectionSignal: "Large-project service terms become part of connection diligence.",
    tariffCostSignal: "Additional billing and risk-allocation terms may apply.",
    cleanEnergySignal: "No data-center-specific renewable mandate in the tracked record.",
    sourceBasis: "Georgia PSC.",
  },
  {
    market: "Ohio",
    trackedDevelopment: "AEP Ohio data center tariff",
    currentStatus: "Effective",
    powerSignal: "Capacity reservation is linked to tariff commitments.",
    interconnectionSignal: "Large-load queue and contracted-capacity requirements are relevant.",
    tariffCostSignal: "Minimum billing and financial requirements directly affect economics.",
    cleanEnergySignal: "No data-center-specific renewable mandate in the tracked record.",
    sourceBasis: "PUCO.",
  },
  {
    market: "Oregon",
    trackedDevelopment: "HB 3546 large energy use facility class",
    currentStatus: "Effective; implementing tariff work follows",
    powerSignal: "Qualifying large users receive distinct service treatment.",
    interconnectionSignal: "Utility implementation matters for service sequencing.",
    tariffCostSignal: "Separate cost-allocation and tariff treatment is required.",
    cleanEnergySignal: "No project-specific procurement term in this tracked record.",
    sourceBasis: "Oregon Legislature.",
  },
  {
    market: "Illinois",
    trackedDevelopment: "Data center incentive intake change",
    currentStatus: "Applications no longer processed as of July 1, 2026",
    powerSignal: "No direct electric-service change in this record.",
    interconnectionSignal: "No direct interconnection change in this record.",
    tariffCostSignal: "No direct utility tariff change; tax economics are affected.",
    cleanEnergySignal: "No new clean-energy requirement in this record.",
    sourceBasis: "Illinois DCEO.",
  },
  {
    market: "Pennsylvania",
    trackedDevelopment: "GRID requirements",
    currentStatus: "Effective state development and permitting framework",
    powerSignal: "Energy responsibility is incorporated into project review.",
    interconnectionSignal: "Infrastructure and permitting commitments can affect project sequence.",
    tariffCostSignal: "Developer commitments require project-specific cost diligence.",
    cleanEnergySignal: "Environmental and energy commitments are part of the framework.",
    sourceBasis: "Pennsylvania DCED.",
  },
  {
    market: "Arizona",
    trackedDevelopment: "APS Extra High Load Factor rate case",
    currentStatus: "Pending",
    powerSignal: "System capability remains project-specific.",
    interconnectionSignal: "Commercial terms are under review while the physical process remains utility-specific.",
    tariffCostSignal: "Large-load rate design remains unresolved in the tracked proceeding.",
    cleanEnergySignal: "No final data-center-specific requirement in the tracked record.",
    sourceBasis: "Arizona Corporation Commission.",
  },
  {
    market: "California",
    trackedDevelopment: "PG&E Electric Rule 30",
    currentStatus: "Interim CPUC-approved transmission-level service pathway",
    powerSignal: "Creates a defined pathway for high-energy transmission-level customers in PG&E territory.",
    interconnectionSignal: "Intended to streamline transmission-level grid connections.",
    tariffCostSignal: "Interim applicants fund necessary transmission infrastructure work upfront.",
    cleanEnergySignal: "No data-center-specific procurement mandate in Rule 30.",
    sourceBasis: "California Public Utilities Commission.",
  },
  {
    market: "Washington",
    trackedDevelopment: "UTC Docket UE-260162",
    currentStatus: "Open policy proceeding",
    powerSignal: "Large-load service planning is under active policy review.",
    interconnectionSignal: "Interconnection conditions are an explicit workshop topic.",
    tariffCostSignal: "Rates and cost sharing are explicit proceeding topics.",
    cleanEnergySignal: "No final new data-center-specific requirement established in this record.",
    sourceBasis: "Washington UTC.",
  },
  {
    market: "Wisconsin",
    trackedDevelopment: "We Energies Very Large Customer tariff",
    currentStatus: "Approved",
    powerSignal: "Very large customers receive service under a dedicated tariff framework.",
    interconnectionSignal: "Utility service and infrastructure readiness remain project-specific.",
    tariffCostSignal: "Long-term tariff and financial requirements apply to qualifying customers.",
    cleanEnergySignal: "The tracked tariff decision focuses on large-load service and cost treatment.",
    sourceBasis: "Public Service Commission of Wisconsin.",
  },
  {
    market: "Michigan",
    trackedDevelopment: "Consumers Energy Rate GPD data center provisions",
    currentStatus: "Approved",
    powerSignal: "Large customers progress through studies and project-specific filings.",
    interconnectionSignal: "Study and commission-review steps are part of service readiness.",
    tariffCostSignal: "Minimum billing, exit-fee, and collateral provisions apply.",
    cleanEnergySignal: "Clean-energy issues are handled through other Michigan proceedings.",
    sourceBasis: "Michigan Public Service Commission.",
  },
  {
    market: "Florida",
    trackedDevelopment: "FPL LLCS-1 and LLCS-2",
    currentStatus: "Approved in FPL settlement",
    powerSignal: "Large-load service is linked to dedicated service agreements and resource planning.",
    interconnectionSignal: "Engineering and contracting steps affect readiness.",
    tariffCostSignal: "LLCS pricing includes large-load-specific rate and take-or-pay terms.",
    cleanEnergySignal: "No universal data-center renewable mandate in the LLCS approval.",
    sourceBasis: "Florida Public Service Commission.",
  },
];
